// Code generated by "github.com/hedhyw/semerr"; DO NOT EDIT.

package grpcerr

import (
	"errors"

	"github.com/hedhyw/semerr/pkg/v1/semerr"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Code returns grpc status code for err.
func Code(err error) codes.Code {
	switch err.(type) {
	case nil:
		return codes.OK
	case semerr.BadRequestError:
		return 3
	case semerr.ForbiddenError:
		return 7
	case semerr.InternalServerError:
		return 2
	case semerr.NotFoundError:
		return 5
	case semerr.ServiceUnavailableError:
		return 14
	case semerr.UnauthorizedError:
		return 16
	}

	code := status.Code(err)
	if code != codes.OK && code != codes.Unknown {
		return code
	}

	if err = errors.Unwrap(err); err == nil {
		return codes.Unknown
	}

	return Code(err)
}
