name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Lint
        run: make lint

      - name: Generate
        run: make generate

      - name: Check generated
        run: git diff --exit-code

      - name: Test
        run: make test

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
